# Generated by Django 4.2 on 2026-08-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Full Stack Developer", max_length=200),
                ),
                ("bio", models.TextField()),
                ("skills", models.TextField(help_text="Comma-separated skills")),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "About",
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="portfolio/"),
                ),
                (
                    "technologies",
                    models.TextField(help_text="Comma-separated technologies"),
                ),
                ("link", models.URLField(blank=True)),
                ("github_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="PersonalInfo",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(default="Other", max_length=100),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(default=80, help_text="0-100"),
        ),
        migrations.DeleteModel(
            name="SkillCategory",
        ),
    ]
